services:
  2grok2api:
    container_name: 2grok2api
    build:
      context: .
      dockerfile: Dockerfile
    image: 2grok2api:local
    ports:
      - "9765:9765"
    environment:
      TZ: Asia/Shanghai
      LOG_LEVEL: INFO
      SERVER_PORT: 9765
      SERVER_WORKERS: 1
      SERVER_STORAGE_TYPE: local
      # SERVER_STORAGE_URL:

      # SERVER_STORAGE_TYPE: (local, redis, mysql, pgsql) default: local
      # SERVER_STORAGE_URL: (local mode is empty) default: empty
      #   Redis: redis://localhost:6379/0 or redis://:password@localhost:6379/0
      #   MySQL: mysql+aiomysql://user:pass@localhost/db
      #   PgSQL: postgresql+asyncpg://user:pass@localhost/db
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
